server:
  port: 8888

spring:
  application:
    name: delivery-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservice
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/
